#!/bin/bash
# Non-empty defaults should be set in server-env
. `dirname $0`/server_env

${ERL} \
    ${EBIN_ARGS} \
    -noinput \
    -setcookie $COOKIE \
    -name serverctl@127.0.0.1 \
    -boot start_clean \
    -s main_ctrl \
    -hidden \
    -extra "$@"
