#!/bin/bash
. `dirname $0`/server_env
## 参数解析
## 参考http://www.cnblogs.com/FrankTan/archive/2010/03/01/1634516.html
## info_msg $@
TEMP=`getopt -o -c:,m: -l config:,nodename:,log_dir:,mode: -n server -- "$@"`

if [ $? != 0 ] ; then
    error_msg "解析选项出错";
fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

while true ; do
    case "$1" in
        -c|--config) 
            CONFIG_FILE=$2;;
        --nodename) 
            NODENAME=$2;;
        --log_dir) 
            LOG_DIR=$2;;
        -m|--mode) 
            MODE=$2;;       
        --) 
            shift ; 
            break ;;
        *) 
            error_msg "UnKnown Option $1";;
    esac
    shift 2
done
## info_msg $@


DATETIME=`date "+%Y%m%d-%H:%M:%S"`
export ERL_CRASH_DUMP=$LOG_DIR/erl_crash_$DATETIME.dump ## for crash_dump

export ERL_MAX_ETS_TABLES=4000 ## default 1400


## 设置ulimit
if [[ $UID == 0 ]]; then
    ulimit -HSn 65535
fi

CONFIG_ARG= #初始化为空
[ -f "${CONFIG_FILE}" ] && CONFIG_ARG="-config ${CONFIG_FILE}"


START_SERVER="-s main start -hongkongresort log_dir \"$LOG_DIR\" "

# ARGS变量
BASE_ARGS=" -smp auto -setcookie $COOKIE +K true +A 120 +W w -boot start_sasl -hidden "
NODENAME_ARGS=" -name ${NODENAME}"

SERVER_CTL="$SCRIPT_DIR/server_ctl --nodename $NODENAME"

started() {
    local ret=`$SERVER_CTL started`
    result=$?
    ## info_msg "result " $result
    info_msg "ret " $ret
    if [[  "$result" == 0 ]]; then
        if [[ $ret == "true" ]]; then
            return 0
        fi
        return 1
    fi
    return 1
}

# 判断节点是否crash
crashed() 
{
    if [ -f ${ERL_CRASH_DUMP} ]; then
        return 0
    fi
    return 1
}

## 注意：\换行后面不可以有空格
start() {
    if started; then
        error_msg "节点$NODENAME已经启动"
    fi
    ${ERL} ${BASE_ARGS} ${EBIN_ARGS} ${START_SERVER} ${CONFIG_ARG} -noinput -detached ${NODENAME_ARGS} 
    result=$?
    while true; do
        if [ $result -ne 0 ]; then
            error_msg "启动失败"
        else
            if started; then
                info_msg "启动完成"
                break
            fi
            if [ -f ${ERL_CRASH_DUMP} ]; then
               error_msg "启动失败，发生crash！"
            else
                sleep 0.01
            fi
        fi
    done
}
live() {
    if started; then
        error_msg "节点$NODENAME已经启动"
    fi
    ${ERL} ${BASE_ARGS} ${EBIN_ARGS} ${START_SERVER} ${CONFIG_ARG} ${NODENAME_ARGS} 
}

attach() {
    if ! started; then
        error_msg "$NODENAME 未启动"
    fi
    ${ERL} ${BASE_ARGS} -name attach$$_$NODENAME -remsh $NODENAME
}

## TODO started
help()
{
    echo "./$0 start"  
    echo "./$0 live"
    echo "./$0 stop"
}
case $MODE in
    'start') 
        start;;
    'started') 
        started;;
    'stop')
        $SERVER_CTL stop;;
    'live')
         live;;
    'attach')
        attach;;
    *)
        help;;
esac

