#!/bin/bash
error_msg() {
    echo -e "`date +"%F %T"` [error] $@"
    exit 1
}

# 打印信息
info_msg() {
    echo -e "`date +"%F %T"` [info] $@"
}

# 打印警告
warning_msg() {
    echo -e "`date +"%F %T"` [warning] $@"
}

# not support link, please use real file path
SCRIPT_DIR=$(cd ${0%/*} && pwd) # 执行脚本所在目录
SCRIPT_NAME=${0##*/} # 可以用来做工具的节点名
SERVER_HOME=${SCRIPT_DIR%/*/*} # 项目的根目录
REL_DIR=${SERVER_HOME%/*} #项目根目录上一级

EBIN_ARGS="-pa ${SERVER_HOME}/ebin ${SERVER_HOME}/deps/*/ebin"

ERL=erl 
COOKIE=hk_resort_erl_cookie_local
